### PR TITLE
added permission for control docker sshkey

### PR DESCRIPTION
**Pull request by acoderninja**
Added the ssh-key permission bug fix.

### CODE REVIEW

**Comment by Link-** [comment]
Fixes #1

**Comment by acoderninja** [comment]
Is everything looks good?

**Comment by acoderninja** [comment]
I am good with this fix.

**Comment by acoderninja** [comment]
If everything looks good, good to merge 👍

**Comment by Link-** [comment]
@acoderninja I'm waiting to find the time to test this locally, sorry for the delay :)

**Comment by Link-** [comment]
Done thank you @acoderninja for the fix!

**Review by Link- — COMMENTED** [review]
🚢

**Pull request merged**
